### ISSUE TITLE
Seperate Repositories for rm2kpng & rm2kfixwatcher

### ISSUE THREAD

**Issue by crunchyegg-gg** [silbinarywolf/rm2kpng#3] opened 2020-11-05 09:19 UTC
This library and tool it was designed for are both lovely, but separating the repositories and having rm2kpng be a submodule within rm2kfixwatcher's own repository would be ideal. It would make it much easier for people to reuse in their own projects.

**Comment by silbinarywolf** [comment] 2020-11-06 04:02
Currently if you `go get -u github.com/silbinarywolf/rm2kpng` you'll just get this library and its `test` folder with no `cmd` folder which is my intended behaviour.

I'm open to doing this, it's just unclear to me what the value is here and what you actually want to achieve.

**Comment by crunchyegg-gg** [comment] 2020-11-07 00:21
The idea was to accommodate for people pulling directly through git or people who are using git for their own projects using this library.

`git clone github.com/silbinarywolf/rm2kpng` would pull only the library where `git clone --recursive github.com/silbinarywolf/rm2kfixwatcher` would pull both the rm2kfixwatcher source and rm2kpng's source in a subdirectory.

If people who want to include just the rm2kpng library in their own projects add the current repository as a git submodule, it would end up pulling both rm2kpng and rm2kfixwatcher.

**Comment by silbinarywolf** [comment] 2020-11-08 01:27
Git Submodules are kinda terrible for managing dependencies and I'm not going to support this hypothetical use-case that a Go programmer probably wouldn't use.

My main personal motivation is that the time+effort convenience on me only having to maintain one repository / CI for this library and tool outweighs the value of splitting things up.

I'm going to close this.

**Closed as completed by silbinarywolf** 2020-11-08 01:27 UTC
